//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityProfiler.Viewer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double WindowTop {
            get {
                return ((double)(this["WindowTop"]));
            }
            set {
                this["WindowTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double WindowLeft {
            get {
                return ((double)(this["WindowLeft"]));
            }
            set {
                this["WindowLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public double WindowHeight {
            get {
                return ((double)(this["WindowHeight"]));
            }
            set {
                this["WindowHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("600")]
        public double WindowWidth {
            get {
                return ((double)(this["WindowWidth"]));
            }
            set {
                this["WindowWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::System.Windows.WindowState WindowState {
            get {
                return ((global::System.Windows.WindowState)(this["WindowState"]));
            }
            set {
                this["WindowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::EntityProfiler.Viewer.Models.ApplicationSession ApplicationSession {
            get {
                return ((global::EntityProfiler.Viewer.Models.ApplicationSession)(this["ApplicationSession"]));
            }
            set {
                this["ApplicationSession"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool OutputWordWrap {
            get {
                return ((bool)(this["OutputWordWrap"]));
            }
            set {
                this["OutputWordWrap"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Connection_AutoStartWhenInitialized {
            get {
                return ((bool)(this["Connection_AutoStartWhenInitialized"]));
            }
            set {
                this["Connection_AutoStartWhenInitialized"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int Connection_RetryConnectInterval {
            get {
                return ((int)(this["Connection_RetryConnectInterval"]));
            }
            set {
                this["Connection_RetryConnectInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Connection_MaxRetryConnect {
            get {
                return ((int)(this["Connection_MaxRetryConnect"]));
            }
            set {
                this["Connection_MaxRetryConnect"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Connection_ConfirmOnCloseConnected {
            get {
                return ((bool)(this["Connection_ConfirmOnCloseConnected"]));
            }
            set {
                this["Connection_ConfirmOnCloseConnected"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Output_DisableLog {
            get {
                return ((bool)(this["Output_DisableLog"]));
            }
            set {
                this["Output_DisableLog"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Information")]
        public global::Serilog.Events.LogEventLevel Output_MinLogLevel {
            get {
                return ((global::Serilog.Events.LogEventLevel)(this["Output_MinLogLevel"]));
            }
            set {
                this["Output_MinLogLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::EntityProfiler.Viewer.PresentationCore.ExtendedTextEditorOptions TextEditor_SqlEditorOptions {
            get {
                return ((global::EntityProfiler.Viewer.PresentationCore.ExtendedTextEditorOptions)(this["TextEditor_SqlEditorOptions"]));
            }
            set {
                this["TextEditor_SqlEditorOptions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::EntityProfiler.Viewer.PresentationCore.ExtendedTextEditorOptions TextEditor_CodeEditorOptions {
            get {
                return ((global::EntityProfiler.Viewer.PresentationCore.ExtendedTextEditorOptions)(this["TextEditor_CodeEditorOptions"]));
            }
            set {
                this["TextEditor_CodeEditorOptions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Profiler_CallStack_OpenFilesInVisualStudio {
            get {
                return ((bool)(this["Profiler_CallStack_OpenFilesInVisualStudio"]));
            }
            set {
                this["Profiler_CallStack_OpenFilesInVisualStudio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Profiler_CallStack_AllowAnyVsInstance {
            get {
                return ((bool)(this["Profiler_CallStack_AllowAnyVsInstance"]));
            }
            set {
                this["Profiler_CallStack_AllowAnyVsInstance"] = value;
            }
        }
    }
}
